DROP DATABASE IF EXISTS street_problems;

CREATE DATABASE street_problems;

USE street_problems;

CREATE TABLE PROBLEMS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ADDRESS VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE USERS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(40) NOT NULL
);


INSERT INTO PROBLEMS VALUES (1, 'Rua 1', 'Buraco 1');
INSERT INTO PROBLEMS VALUES (2, 'Rua 2', 'Buraco 2');
INSERT INTO PROBLEMS VALUES (3, 'Rua 3', 'Buraco 3');

INSERT INTO USERS VALUES (1, 'admin1', SHA1('senha'));
INSERT INTO USERS VALUES (2, 'admin2', SHA1('senha'));